name: Bug Report
description: Report a bug.
labels: ["bug"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe your issue
      description: Describe what happened. If possible, please attach a screenshot.
    validations:
      required: true
  - type: input
    id: obs-version
    attributes:
      label: Streaming software version
      description: What version of OBS (or other streaming software) are you using?
      placeholder: "OBS Studio 31.0.1"
    validations:
      required: true
  - type: input
    id: widget-url
    attributes:
      label: Widget URL
      description: If the issue occurs in the widget, please add your generated link here. (Optional)
      placeholder: "https://widget.mxgic1337.xyz/widget/?player_id=24180323-d946-4bb7-a334-be3e96fcac05"
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Select a version
      description: In which version the issue happened?
      options:
        - Stable
        - Experimental
      default: 0
    validations:
      required: true
